services:
  backend:
    build: ./backend
    container_name: deepfake-detector-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/__pycache__
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - deepfake-network

  frontend:
    build: ./frontend
    container_name: deepfake-detector-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - deepfake-network

networks:
  deepfake-network:
    driver: bridge
